# Generated by Django 4.1 on 2022-12-03 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('dob', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Format:yyyy-mm-dd', verbose_name='Birth Date')),
            ],
        ),
    ]
